version: "3.8"
services:
  backend:
    build:
      dockerfile: ./docker/Dockerfile
      context: .
    ports:
      - 80:80
    volumes:
      - ./:/var/www/html
      - ./docker/php-overrides.ini:/usr/local/etc/php/conf.d/php-overrides.ini
